import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";

/**
 * GET /api/playbooks/available-items
 * Get all active specs (by scope) and prompt templates for building playbooks
 */
export async function GET(request: NextRequest) {
  try {
    // Note: CALLER specs removed - they are auto-generated by the learning system
    const [domainSpecs, systemSpecs, promptTemplates] = await Promise.all([
      // Domain specs (DOMAIN scope)
      prisma.analysisSpec.findMany({
        where: { isActive: true, scope: "DOMAIN" },
        orderBy: [{ domain: "asc" }, { priority: "desc" }, { name: "asc" }],
        select: {
          id: true,
          slug: true,
          name: true,
          description: true,
          scope: true,
          specType: true,
          outputType: true,
          specRole: true,
          domain: true,
          priority: true,
          _count: {
            select: { triggers: true },
          },
        },
      }),

      // System specs (SYSTEM scope) - include ALL, even inactive ones
      // UI will show inactive status and prevent enabling
      prisma.analysisSpec.findMany({
        where: { scope: "SYSTEM" },
        orderBy: [{ domain: "asc" }, { priority: "desc" }, { name: "asc" }],
        select: {
          id: true,
          slug: true,
          name: true,
          description: true,
          scope: true,
          specType: true,
          outputType: true,
          specRole: true,
          domain: true,
          priority: true,
          isActive: true,
          config: true,
          _count: {
            select: { triggers: true },
          },
        },
      }),

      // Prompt templates
      prisma.promptTemplate.findMany({
        where: { isActive: true },
        orderBy: { name: "asc" },
        select: {
          id: true,
          slug: true,
          name: true,
          description: true,
          version: true,
        },
      }),
    ]);

    return NextResponse.json({
      ok: true,
      callerSpecs: [], // Deprecated - CALLER specs are auto-generated
      domainSpecs,
      systemSpecs,
      promptTemplates,
      counts: {
        callerSpecs: 0,
        domainSpecs: domainSpecs.length,
        systemSpecs: systemSpecs.length,
        promptTemplates: promptTemplates.length,
      },
    });
  } catch (error: any) {
    console.error("Error fetching available items:", error);
    return NextResponse.json(
      { ok: false, error: error?.message || "Failed to fetch available items" },
      { status: 500 }
    );
  }
}
