/**
 * AUTO-GENERATED FROM DATABASE
 * DO NOT EDIT MANUALLY
 * Generated: 2026-02-09T19:03:52.456Z
 *
 * This file is generated by scripts/generate-registry.ts at build time.
 * The source of truth is the Parameter table in the database.
 */

import * as fs from "fs";
import * as path from "path";

// ============================================================================
// TYPES
// ============================================================================

export interface ParameterDefinition {
  parameterId: string;
  name: string;
  definition: string;
  domainGroup: string;
  defaultTarget: number;
  interpretationHigh?: string;
  interpretationLow?: string;
  aliases?: string[];
}

export interface ParameterRegistry {
  version: string;
  description: string;
  parameters: ParameterDefinition[];
  generatedAt: string;
}

// ============================================================================
// PARAMETER CONSTANTS
// ============================================================================

/**
 * Behavior parameter IDs - use these instead of hardcoding strings.
 * Generated from database at build time.
 */
export const PARAMS = {
  abstract_vs_concrete: "abstract-vs-concrete",
  adapt_to_feedback_style: "adapt_to_feedback_style",
  adapt_to_interaction_style: "adapt_to_interaction_style",
  adapt_to_learning_style: "adapt_to_learning_style",
  adapt_to_pace_preference: "adapt_to_pace_preference",
  adapt_to_question_frequency: "adapt_to_question_frequency",
  aggregate_profile: "aggregate_profile",
  agreeableness_adaptation: "agreeableness_adaptation",
  analogy_usage: "analogy-usage",
  application_adaptation: "application_adaptation",
  application_score: "application_score",
  auditory_adaptation: "auditory_adaptation",
  B5_A: "B5-A",
  B5_C: "B5-C",
  B5_E: "B5-E",
  B5_N: "B5-N",
  B5_O: "B5-O",
  BEH_ABSTRACT_OK: "BEH-ABSTRACT-OK",
  BEH_ACTION_VERBS: "BEH-ACTION-VERBS",
  BEH_ADVANCE_READINESS: "BEH-ADVANCE-READINESS",
  BEH_ANALOGY_USAGE: "BEH-ANALOGY-USAGE",
  BEH_APPROACH_SWITCHING: "BEH-APPROACH-SWITCHING",
  BEH_CHALLENGE_LEVEL: "BEH-CHALLENGE-LEVEL",
  BEH_CHECK_FOR_UNDERSTANDING: "BEH-CHECK-FOR-UNDERSTANDING",
  BEH_CONCEPT_DENSITY: "BEH-CONCEPT-DENSITY",
  BEH_CONVERSATIONAL_DEPTH: "BEH-CONVERSATIONAL-DEPTH",
  BEH_CONVERSATIONAL_TONE: "BEH-CONVERSATIONAL-TONE",
  BEH_DEFINITION_PRECISION: "BEH-DEFINITION-PRECISION",
  BEH_DIAGRAM_LANGUAGE: "BEH-DIAGRAM-LANGUAGE",
  BEH_DIRECTNESS: "BEH-DIRECTNESS",
  BEH_EMPATHY_RATE: "BEH-EMPATHY-RATE",
  BEH_EXAMPLE_RICHNESS: "BEH-EXAMPLE-RICHNESS",
  BEH_EXPLANATION_VARIETY: "BEH-EXPLANATION-VARIETY",
  BEH_FEELING_LANGUAGE: "BEH-FEELING-LANGUAGE",
  BEH_FORMALITY: "BEH-FORMALITY",
  BEH_FOUNDATION_FOCUS: "BEH-FOUNDATION-FOCUS",
  BEH_GUIDED_PRACTICE: "BEH-GUIDED-PRACTICE",
  BEH_IMAGERY_DENSITY: "BEH-IMAGERY-DENSITY",
  BEH_INSIGHT_FREQUENCY: "BEH-INSIGHT-FREQUENCY",
  BEH_INTELLECTUAL_CHALLENGE: "BEH-INTELLECTUAL-CHALLENGE",
  BEH_INTERLEAVING: "BEH-INTERLEAVING",
  BEH_LIST_STRUCTURE: "BEH-LIST-STRUCTURE",
  BEH_MEMORY_REFERENCE: "BEH-MEMORY-REFERENCE",
  BEH_MODALITY_CONSISTENCY: "BEH-MODALITY-CONSISTENCY",
  BEH_MODALITY_VARIETY: "BEH-MODALITY-VARIETY",
  BEH_NEW_CONTENT_RATE: "BEH-NEW-CONTENT-RATE",
  BEH_NUANCE_EXPLORATION: "BEH-NUANCE-EXPLORATION",
  BEH_PACE_MATCH: "BEH-PACE-MATCH",
  BEH_PATIENCE_LEVEL: "BEH-PATIENCE-LEVEL",
  BEH_PAUSE_TOLERANCE: "BEH-PAUSE-TOLERANCE",
  BEH_PRACTICE_EXERCISES: "BEH-PRACTICE-EXERCISES",
  BEH_PRACTICE_RATIO: "BEH-PRACTICE-RATIO",
  BEH_PREREQUISITE_CALLBACK: "BEH-PREREQUISITE-CALLBACK",
  BEH_PROACTIVE: "BEH-PROACTIVE",
  BEH_PROBING_QUESTIONS: "BEH-PROBING-QUESTIONS",
  BEH_PRODUCTIVE_STRUGGLE: "BEH-PRODUCTIVE-STRUGGLE",
  BEH_QUESTION_RATE: "BEH-QUESTION-RATE",
  BEH_REAL_WORLD_EXAMPLES: "BEH-REAL-WORLD-EXAMPLES",
  BEH_REPETITION_FREQUENCY: "BEH-REPETITION-FREQUENCY",
  BEH_REPETITION_OFFER: "BEH-REPETITION-OFFER",
  BEH_RESPECT_EXPERIENCE: "BEH-RESPECT-EXPERIENCE",
  BEH_RESPONSE_LEN: "BEH-RESPONSE-LEN",
  BEH_RHYTHM_ATTENTION: "BEH-RHYTHM-ATTENTION",
  BEH_SCAFFOLDING: "BEH-SCAFFOLDING",
  BEH_SPACED_RETRIEVAL_PRIORITY: "BEH-SPACED-RETRIEVAL-PRIORITY",
  BEH_SPATIAL_METAPHOR: "BEH-SPATIAL-METAPHOR",
  BEH_STORY_INVITATION: "BEH-STORY-INVITATION",
  BEH_TERMINOLOGY_FORMAL: "BEH-TERMINOLOGY-FORMAL",
  BEH_TURN_LENGTH: "BEH-TURN-LENGTH",
  BEH_VERBAL_ELABORATION: "BEH-VERBAL-ELABORATION",
  BEH_WARMTH: "BEH-WARMTH",
  BEH_WORKED_EXAMPLES: "BEH-WORKED-EXAMPLES",
  BEH_WRITTEN_ALTERNATIVE: "BEH-WRITTEN-ALTERNATIVE",
  call_frequency_adaptation: "call_frequency_adaptation",
  check_for_understanding: "check-for-understanding",
  chunk_size: "chunk-size",
  communication_complexity_adaptation: "communication_complexity_adaptation",
  COMP_DEPTH_PREFERENCE: "COMP-DEPTH-PREFERENCE",
  COMP_ENERGY: "COMP-ENERGY",
  COMP_ENGAGEMENT: "COMP-ENGAGEMENT",
  COMP_MOOD: "COMP-MOOD",
  composite_reward: "composite_reward",
  comprehension_adaptation: "comprehension_adaptation",
  comprehension_score: "comprehension_score",
  COMP_REMINISCENCE: "COMP-REMINISCENCE",
  concept_density: "concept-density",
  concept_exposure: "concept_exposure",
  conscientiousness_adaptation: "conscientiousness_adaptation",
  context_setting_quality: "context_setting_quality",
  CONV_DOM: "CONV_DOM",
  CONV_PACE: "CONV_PACE",
  CP_004: "CP-004",
  crisis_detection_score: "crisis_detection_score",
  default_targets_quality: "default_targets_quality",
  directness_actual: "directness_actual",
  empathy_expression: "empathy_expression",
  engagement_adaptation: "engagement_adaptation",
  engagement_prompts: "engagement-prompts",
  engagement_reward: "engagement_reward",
  engagement_trend_score: "engagement_trend_score",
  engagement_with_examples: "engagement_with_examples",
  error_elaboration: "error-elaboration",
  example_richness: "example-richness",
  explanation_depth: "explanation-depth",
  exploration_structure: "exploration_structure",
  extraversion_adaptation: "extraversion_adaptation",
  formality_actual: "formality_actual",
  formality_level: "formality-level",
  goal_discovery_quality: "goal_discovery_quality",
  goal_progress_reward: "goal_progress_reward",
  insight_quality: "insight_quality",
  kinesthetic_adaptation: "kinesthetic_adaptation",
  learning_progress_score: "learning_progress_score",
  learning_reward: "learning_reward",
  learning_velocity_adaptation: "learning_velocity_adaptation",
  mastery_adaptation: "mastery_adaptation",
  module_introduction: "module_introduction",
  module_mastery: "module_mastery",
  multimodal_adaptation: "multimodal_adaptation",
  neuroticism_adaptation: "neuroticism_adaptation",
  openness_adaptation: "openness_adaptation",
  pace_indicators: "pace_indicators",
  pacing_actual: "pacing_actual",
  pause_for_questions: "pause-for-questions",
  preference_elicitation_quality: "preference_elicitation_quality",
  prerequisite_adaptation: "prerequisite_adaptation",
  prerequisite_check: "prerequisite_check",
  question_asking_rate: "question_asking_rate",
  rapport_reward: "rapport_reward",
  reading_writing_adaptation: "reading_writing_adaptation",
  repetition_frequency: "repetition-frequency",
  response_empathy_score: "response_empathy_score",
  response_length_preference: "response_length_preference",
  response_length_score: "response_length_score",
  review_adaptation: "review_adaptation",
  review_status: "review_status",
  safety_compliance_score: "safety_compliance_score",
  scaffolding: "scaffolding",
  socratic_questioning: "socratic-questioning",
  student_application_score: "student_application_score",
  style_consistency_score: "style_consistency_score",
  target_alignment_score: "target_alignment_score",
  TONE_ASSERT: "TONE_ASSERT",
  tutor_fidelity_score: "tutor_fidelity_score",
  tutor_intro_score: "tutor_intro_score",
  tutor_sequence_score: "tutor_sequence_score",
  VARK_A: "VARK-A",
  VARK_K: "VARK-K",
  VARK_PROFILE: "VARK-PROFILE",
  VARK_R: "VARK-R",
  VARK_V: "VARK-V",
  visual_adaptation: "visual_adaptation",
  warmth_actual: "warmth_actual",
  welcome_quality: "welcome_quality",
} as const;

/**
 * Personality trait parameter IDs
 */
export const TRAITS = {
  B5_A: "B5-A",
  B5_C: "B5-C",
  B5_E: "B5-E",
  B5_N: "B5-N",
  B5_O: "B5-O",
} as const;

/**
 * Canonical spec IDs
 */
export const SPECS = {
  spec_adapt_curr_001: "spec-adapt-curr-001",
  spec_adapt_eng_001: "spec-adapt-eng-001",
  spec_adapt_learn_001: "spec-adapt-learn-001",
  spec_adapt_pers_001: "spec-adapt-pers-001",
  spec_adapt_vark_001: "spec-adapt-vark-001",
  spec_ca_001: "spec-ca-001",
  spec_coach_001: "spec-coach-001",
  spec_comp_001: "spec-comp-001",
  spec_companion_001: "spec-companion-001",
  spec_comp_cd_001: "spec-comp-cd-001",
  spec_comp_cg_001: "spec-comp-cg-001",
  spec_comp_cp_001: "spec-comp-cp-001",
  spec_comp_ew_001: "spec-comp-ew-001",
  spec_comp_gg_001: "spec-comp-gg-001",
  spec_comp_ie_001: "spec-comp-ie-001",
  spec_comp_insight_001: "spec-comp-insight-001",
  spec_comp_is_001: "spec-comp-is-001",
  spec_comp_ix_001: "spec-comp-ix-001",
  spec_comp_lc_001: "spec-comp-lc-001",
  spec_comp_mc_001: "spec-comp-mc-001",
  spec_comp_pp_001: "spec-comp-pp-001",
  spec_comp_re_001: "spec-comp-re-001",
  spec_curr_001: "spec-curr-001",
  spec_curr_fs_l2_001: "spec-curr-fs-l2-001",
  spec_goal_001: "spec-goal-001",
  spec_guard_001: "spec-guard-001",
  spec_guard_voicemail_001: "spec-guard-voicemail-001",
  spec_init_001: "spec-init-001",
  spec_inject_001: "spec-inject-001",
  spec_learn_prof_001: "spec-learn-prof-001",
  spec_learn_style_001: "spec-learn-style-001",
  spec_mem_001: "spec-mem-001",
  spec_pers_001: "spec-pers-001",
  spec_qm_content_001: "spec-qm-content-001",
  spec_rew_001: "spec-rew-001",
  spec_session_001: "spec-session-001",
  spec_style_001: "spec-style-001",
  spec_supv_001: "spec-supv-001",
  spec_tut_001: "spec-tut-001",
  spec_tut_qm_001: "spec-tut-qm-001",
  spec_tut_wnf_001: "spec-tut-wnf-001",
  spec_vark_001: "spec-vark-001",
  spec_voice_001: "spec-voice-001",
  spec_wnf_content_001: "spec-wnf-content-001",
} as const;

// ============================================================================
// PARAMETER GROUPINGS (by domain)
// ============================================================================

export const PARAM_GROUPS = {
  COMMUNICATION_STYLE: [
    
  ] as const,
  ENGAGEMENT_APPROACH: [
    "BEH-TURN-LENGTH", "BEH-WARMTH", "call_frequency_adaptation", "communication_complexity_adaptation", "CONV_DOM", "CONV_PACE", "CP-004", "engagement_adaptation", "learning_velocity_adaptation", "TONE_ASSERT"
  ] as const,
  ADAPTABILITY: [
    
  ] as const,
  EMPATHY: [
    
  ] as const,
  PERSONALITY_TRAITS: [
    "B5-A", "B5-C", "B5-E", "B5-N", "B5-O"
  ] as const,
} as const;

// ============================================================================
// TRAIT NAME MAPPING
// ============================================================================

export const TRAIT_NAMES: Record<string, string> = {
  "B5-A": "agreeableness",
  "B5-C": "conscientiousness",
  "B5-E": "extraversion",
  "B5-N": "neuroticism",
  "B5-O": "openness",
} as const;

// ============================================================================
// RUNTIME HELPERS (load from database at runtime)
// ============================================================================

let _paramMap: Map<string, ParameterDefinition> | null = null;

export async function loadParameterRegistry(): Promise<ParameterRegistry> {
  const { PrismaClient } = await import("@prisma/client");
  const prisma = new PrismaClient();

  const params = await prisma.parameter.findMany({
    where: {
      isCanonical: true,
      deprecatedAt: null,
    },
    orderBy: { parameterId: "asc" },
  });

  await prisma.$disconnect();

  return {
    version: "1.0",
    description: "Canonical registry of behavior parameters from database",
    parameters: params.map((p) => ({
      parameterId: p.parameterId,
      name: p.name,
      definition: p.definition || "",
      domainGroup: p.domainGroup,
      defaultTarget: p.defaultTarget,
      interpretationHigh: p.interpretationHigh || undefined,
      interpretationLow: p.interpretationLow || undefined,
      aliases: p.aliases && p.aliases.length > 0 ? p.aliases : undefined,
    })),
    generatedAt: new Date().toISOString(),
  };
}

export type ParamId = (typeof PARAMS)[keyof typeof PARAMS];
export type TraitId = (typeof TRAITS)[keyof typeof TRAITS];
export type SpecId = (typeof SPECS)[keyof typeof SPECS];
