"use client";

import React, { useMemo, useState, useEffect, useRef, useCallback } from "react";
import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";

type NavItem = {
  href: string;
  label: string;
  icon?: string;
  working?: boolean;
  indent?: boolean; // For sub-items
};

type NavSection = {
  id: string;
  title?: string;
  items: NavItem[];
  dividerAfter?: boolean;
  collapsible?: boolean;
  defaultCollapsed?: boolean;
};

export default function SidebarNav({
  collapsed: externalCollapsed,
  onToggle: externalOnToggle,
}: {
  collapsed?: boolean;
  onToggle?: () => void;
} = {}) {
  const pathname = usePathname();
  const router = useRouter();
  const [mounted, setMounted] = useState(false);
  const [internalCollapsed, setInternalCollapsed] = useState(false);
  const [focusedIndex, setFocusedIndex] = useState<number>(-1);
  const navRef = useRef<HTMLElement>(null);

  // Use external state if provided, otherwise use internal state
  const collapsed = externalCollapsed ?? internalCollapsed;
  const onToggle = externalOnToggle ?? (() => setInternalCollapsed(prev => !prev));

  useEffect(() => {
    setMounted(true);
  }, []);

  const sections: NavSection[] = useMemo(
    () => [
      // ============================================================
      // ANALYZE: Primary workflow - the main thing users do
      // ============================================================
      {
        id: "analyze",
        items: [
          { href: "/analyze", label: "Analyze", icon: "🔬", working: true },
          { href: "/prompts", label: "Prompts", icon: "📝", working: true },
        ],
        collapsible: false,
        dividerAfter: true,
      },

      // ============================================================
      // PRIMARY: Quick access to operational views
      // ============================================================
      {
        id: "primary",
        title: "Operations",
        items: [
          { href: "/cockpit", label: "Cockpit", icon: "🧭", working: true },
          { href: "/flow", label: "Flow", icon: "🔀", working: true },
          { href: "/ops", label: "Ops", icon: "🛠️", working: true },
          { href: "/guide", label: "Guide", icon: "📖", working: true },
        ],
        collapsible: true,
        defaultCollapsed: false,
        dividerAfter: true,
      },

      // ============================================================
      // PLAYBOOKS: Domain segmentation and playbook management
      // Domains → Playbooks → Specs (by scope) + Prompt Templates
      // ============================================================
      {
        id: "playbooks",
        title: "Playbooks",
        items: [
          // Domain segmentation (Tutor, Support, Sales, Wellness)
          { href: "/domains", label: "Domains", icon: "🌐", working: true },
          // Playbooks (bundles of specs + templates per domain)
          { href: "/playbooks", label: "Playbooks", icon: "📚", working: true },
          // Specifications by scope (simplified views, scope filter hidden)
          // Note: CALLER specs are auto-generated by learning, not shown here
          { href: "/analysis-specs?scope=DOMAIN&locked=1", label: "Domain Specs", icon: "🏢", working: true },
          { href: "/analysis-specs?scope=SYSTEM&locked=1", label: "System Specs", icon: "🛡️", working: true },
          // Prompt templates for output composition
          { href: "/prompt-templates", label: "Prompt Templates", icon: "📝", working: true },
          // Reference: Template variables and key prefixes
          { href: "/data-dictionary", label: "Data Dictionary", icon: "📖", working: true },
        ],
        collapsible: true,
        defaultCollapsed: false,
        dividerAfter: true,
      },

      // ============================================================
      // SETUP: Define what to measure and how to adapt
      // This is configuration that rarely changes after initial setup
      // Flow: Parameters → AnalysisSpecs → PromptSlugs
      // ============================================================
      {
        id: "setup",
        title: "Setup",
        items: [
          // Step 1: Define parameters (dimensions to measure)
          { href: "/admin", label: "Parameters", icon: "📐", working: true },
          // Step 2: Define HOW to measure each parameter (scoring criteria)
          { href: "/analysis-specs", label: "All Specs", icon: "🎯", working: true },
          // Step 3: Define WHAT to say based on measurements (adaptation prompts)
          { href: "/prompt-slugs", label: "Prompt Slugs", icon: "🔀", working: true },
          // Step 4: Define static prompt blocks (system prompts, instructions)
          { href: "/prompt-blocks", label: "Prompt Blocks", icon: "🧱", working: true },
          // Step 5: Configure memory injection policies
          { href: "/memories", label: "Memory Config", icon: "🧠", working: true },
        ],
        collapsible: true,
        defaultCollapsed: true,
      },

      // ============================================================
      // SOURCES: Raw input data that feeds the pipeline
      // Knowledge docs → chunks/vectors
      // Call transcripts → caller profiles
      // ============================================================
      {
        id: "sources",
        title: "Sources",
        items: [
          // Knowledge base documents (PDFs, markdown, etc.)
          { href: "/knowledge-docs", label: "Knowledge Docs", icon: "📚", working: true },
          // Raw call transcripts
          { href: "/transcripts", label: "Transcripts", icon: "🎙️", working: true },
        ],
        collapsible: true,
        defaultCollapsed: false,
      },

      // ============================================================
      // PROCESSING: Derived data from sources
      // Knowledge → Chunks → Vectors → Artifacts
      // Transcripts → Calls → Callers
      // ============================================================
      {
        id: "processing",
        title: "Processing",
        items: [
          // Chunked knowledge for RAG
          { href: "/chunks", label: "Chunks", icon: "📄", working: true },
          // Vector embeddings for similarity search
          { href: "/vectors", label: "Vectors", icon: "🔢", working: true },
          // Extracted knowledge artifacts
          { href: "/knowledge-artifacts", label: "Artifacts", icon: "💎", working: true },
        ],
        collapsible: true,
        defaultCollapsed: true,
      },

      // ============================================================
      // DATA: View callers and calls (results of analysis)
      // ============================================================
      {
        id: "data",
        title: "Data",
        items: [
          // Callers (people) and their accumulated profiles
          { href: "/callers", label: "Callers", icon: "👥", working: true },
          // Individual calls with analysis results
          { href: "/calls", label: "Calls", icon: "📞", working: true },
        ],
        collapsible: true,
        defaultCollapsed: false,
      },

      // ============================================================
      // ANALYSIS CONFIG: Configure how analysis runs
      // ============================================================
      {
        id: "analysis-config",
        title: "Analysis Config",
        items: [
          // Analysis profiles (which specs to run, thresholds)
          { href: "/analysis-profiles", label: "Profiles", icon: "📊", working: true },
          // Analysis run history and results
          { href: "/analysis-runs", label: "Run History", icon: "▶️", working: true },
          // Test analysis on sample text
          { href: "/analysis-test", label: "Test Lab", icon: "🧪", working: true },
        ],
        collapsible: true,
        defaultCollapsed: true,
      },

      // ============================================================
      // CONFIG: System configuration and agent management
      // Agents, control sets, global settings
      // ============================================================
      {
        id: "config",
        title: "Config",
        items: [
          // Agent definitions and run history
          { href: "/agents", label: "Agents", icon: "🤖", working: true },
          // Run configurations for batch processing
          { href: "/run-configs", label: "Run Configs", icon: "📦", working: true },
          // Behavior targets for REWARD op
          { href: "/behavior-targets", label: "Behavior Targets", icon: "🎯", working: true },
          // Global settings library
          { href: "/settings-library", label: "Settings", icon: "⚙️", working: true },
        ],
        collapsible: true,
        defaultCollapsed: true,
      },
    ],
    []
  );

  // section collapsed state (independent from global sidebar collapse)
  const [collapsedSections, setCollapsedSections] = useState<Record<string, boolean>>(() => {
    const initial: Record<string, boolean> = {};
    for (const s of sections) {
      if (s.collapsible) initial[s.id] = !!s.defaultCollapsed;
    }
    return initial;
  });

  const isActive = (href: string) => {
    if (!mounted || !pathname) return false;
    return pathname === href || pathname.startsWith(href + "/");
  };

  const toggleSection = (id: string) => {
    setCollapsedSections((prev) => ({ ...prev, [id]: !prev[id] }));
  };

  // Flatten all visible nav items for keyboard navigation
  const flatNavItems = useMemo(() => {
    const items: { href: string; label: string }[] = [];
    for (const section of sections) {
      const sectionIsCollapsed = section.collapsible && section.title ? !!collapsedSections[section.id] : false;
      if (!sectionIsCollapsed) {
        for (const item of section.items) {
          items.push({ href: item.href, label: item.label });
        }
      }
    }
    return items;
  }, [sections, collapsedSections]);

  // Handle keyboard navigation
  const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
    if (flatNavItems.length === 0) return;

    if (e.key === "ArrowDown") {
      e.preventDefault();
      setFocusedIndex(prev => (prev + 1) % flatNavItems.length);
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setFocusedIndex(prev => (prev - 1 + flatNavItems.length) % flatNavItems.length);
    } else if (e.key === "Enter" && focusedIndex >= 0) {
      e.preventDefault();
      const item = flatNavItems[focusedIndex];
      if (item) {
        router.push(item.href);
      }
    }
  }, [flatNavItems, focusedIndex, router]);

  // Focus the link when focusedIndex changes
  useEffect(() => {
    if (focusedIndex >= 0 && navRef.current) {
      const links = navRef.current.querySelectorAll('a[data-nav-item]');
      const link = links[focusedIndex] as HTMLElement;
      if (link) {
        link.focus();
      }
    }
  }, [focusedIndex]);

  // Handle navigation for links with query params on same route
  // Next.js useSearchParams should automatically react to URL changes,
  // but we use replace to ensure the URL updates cleanly
  const handleNavClick = (e: React.MouseEvent<HTMLAnchorElement>, href: string) => {
    const [targetPath] = href.split('?');
    const currentPath = pathname;

    // If navigating to same path but different query params, use router.replace
    // This ensures clean URL update without adding to history stack
    if (targetPath === currentPath) {
      e.preventDefault();
      router.replace(href);
    }
  };

  return (
    <div className="flex h-full flex-col bg-white p-3 text-neutral-900 overflow-hidden">
      <div className="mb-3 flex items-center justify-between gap-2">
        {!collapsed ? (
          <div className="text-sm font-extrabold tracking-tight text-neutral-900">HF Admin</div>
        ) : (
          <div className="w-6" />
        )}

        <button
          type="button"
          onClick={onToggle}
          aria-label="Toggle sidebar"
          className="inline-flex items-center justify-center rounded-md border border-neutral-300 bg-white px-2 py-1 text-sm text-neutral-900 hover:bg-neutral-50 focus:outline-none focus:ring-2 focus:ring-indigo-200"
        >
          {collapsed ? "→" : "←"}
        </button>
      </div>

      {/* Scrollable nav area */}
      <div className="flex min-h-0 flex-1 flex-col overflow-y-auto pr-1">
        <nav
          ref={navRef}
          className="flex flex-col gap-3"
          onKeyDown={handleKeyDown}
          role="navigation"
          aria-label="Main navigation"
        >
          {sections.map((section) => {
            const canCollapse = !!section.collapsible && !!section.title;
            const sectionIsCollapsed = canCollapse ? !!collapsedSections[section.id] : false;

            return (
              <div key={section.id} className="flex flex-col">
                {section.title && !collapsed ? (
                  <button
                    type="button"
                    onClick={() => (canCollapse ? toggleSection(section.id) : undefined)}
                    className={
                      "flex items-center justify-between gap-2 rounded-md px-2 pb-1 text-left text-[11px] font-semibold uppercase tracking-wide text-neutral-600 " +
                      (canCollapse ? "hover:bg-neutral-50" : "")
                    }
                    aria-label={
                      canCollapse
                        ? sectionIsCollapsed
                          ? `Expand ${section.title}`
                          : `Collapse ${section.title}`
                        : section.title
                    }
                    disabled={!canCollapse}
                  >
                    <span>{section.title}</span>
                    {canCollapse ? (
                      <span className="text-[12px] leading-none text-neutral-500" aria-hidden>
                        {sectionIsCollapsed ? "▸" : "▾"}
                      </span>
                    ) : null}
                  </button>
                ) : null}

                {sectionIsCollapsed ? null : (
                  <div className="flex flex-col gap-0.5">
                    {section.items.map((l) => {
                      const active = isActive(l.href);
                      const isSubItem = l.indent && !l.icon;
                      const itemIndex = flatNavItems.findIndex(fi => fi.href === l.href);
                      const isFocused = itemIndex === focusedIndex;
                      return (
                        <Link
                          key={l.href}
                          href={l.href}
                          title={collapsed ? l.label : undefined}
                          data-nav-item
                          tabIndex={0}
                          onClick={(e) => handleNavClick(e, l.href)}
                          onFocus={() => setFocusedIndex(itemIndex)}
                          className={
                            "flex items-center gap-2 rounded-md transition-colors focus:outline-none focus:ring-2 focus:ring-indigo-200 " +
                            (isSubItem
                              ? "pl-7 pr-2 py-1.5 text-[13px] "
                              : "px-2 py-2 text-sm ") +
                            (active
                              ? "bg-indigo-600 text-white font-semibold"
                              : isFocused
                              ? "bg-neutral-100 text-neutral-900 font-medium"
                              : isSubItem
                              ? "text-neutral-600 hover:bg-neutral-100 hover:text-neutral-900"
                              : l.working
                              ? "text-neutral-900 font-medium hover:bg-neutral-100"
                              : "text-neutral-900 hover:bg-neutral-100")
                          }
                        >
                          {l.icon && (
                            <span className={"text-base " + (active ? "opacity-100" : "opacity-80")} aria-hidden>
                              {l.icon}
                            </span>
                          )}
                          {!collapsed ? <span className="truncate">{l.label}</span> : null}
                        </Link>
                      );
                    })}
                  </div>
                )}

                {section.dividerAfter ? <div className="my-3 border-t border-neutral-300" /> : null}
              </div>
            );
          })}
        </nav>

        <div className="mt-3">
          {!collapsed ? <div className="text-center text-[11px] text-neutral-600">HumanFirst Admin</div> : null}
        </div>
      </div>
    </div>
  );
}
